CREATE DATABASE IF NOT EXISTS gamesdb;
USE gamesdb;

DROP TABLE IF EXISTS customers;

CREATE TABLE IF NOT EXISTS customers (
id INT PRIMARY KEY AUTO_INCREMENT,
first_name VARCHAR(20) NOT NULL,
last_name VARCHAR(20),
age INT NOT NULL
);

DROP TABLE IF EXISTS orders;

CREATE TABLE IF NOT EXISTS orders (
id INT PRIMARY KEY AUTO_INCREMENT,
cust_id INT NOT NULL,
FOREIGN KEY (cust_id) REFERENCES customers(id)
);
